version: "3.8"
services:
  mongo:
    container_name: mongo-container
    image: mongo:4
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    build: .
    image: clean-node-api
    restart: always
    command: npm start
    volumes:
      - ./dist:/usr/clean-node/dist
    ports:
      - "3000:3000"
    links:
      - mongo