version: "3.8"
services:
  mongo:
    container_name: mongo-container
    image: mongo:4
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:16
    working_dir: /usr/clean-node
    restart: always
    command: bash -c "npm set-script prepare '' && npm install --only=prod && npm run debug"
    volumes:
      - ./dist:/usr/clean-node/dist
      - ./package.json:/usr/clean-node/package.json
    ports:
      - "3000:3000"
      - "9222:9222"
    links:
      - mongo