version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.6
  node: circleci/node@5.0.2

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn install
      - run: yarn test:coveralls
      - coveralls/upload:
          parallel: true
          flag_name: Test Coverage
          verbose: true

  done:
    executor:
      name: node/default
    steps:
      - coveralls/upload:
          parallel_finished: true

workflows:
  build_test:
    jobs:
      - build
      - done:
          requires: [build]
