version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  build:
    executor:
      name: node/default
      tag: '18.12.0'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: echo "deb http://security.ubuntu.com/ubuntu focal-security main" | sudo tee /etc/apt/sources.list.d/focal-security.list
      - run: sudo apt-get update && sudo apt-get install libssl1.1
      - run: yarn test:coveralls

workflows:
  build_test:
    jobs:
      - build