version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  build:
    executor:
      name: node/default
      tag: '18.12.0'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: sudo apt-get update && sudo cp /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.2 /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
      - run: yarn test:coveralls

workflows:
  build_test:
    jobs:
      - build